project:
  type: website

language: web_resource/ko.yml
date-format: iso

website:
  title: "목차"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.ipynb
        text: "들어가는 글"
      - section: "데이터 플랫폼이란"
      - section: "데이터 처리 기초"
      - section: "파일기반 데이터 저장소"
        contents:
          - contents/datastore/index.ipynb
          - contents/datastore/google_sheets.ipynb
      - section: "관계형 데이터베이스"
      - section: "데이터 분산 처리"
        contents:
          - section: "Dask"
          - section: "Ray"
          - section: "Modin"
      - section: "데이터 추출, 변환, 적재"
      - section: "스케줄링"

format:
  html:
    theme: cosmo
    css: web_resource/styles.css
    toc: true
