project:
  type: website

language: web_resource/ko.yml
date-format: iso

website:
  title: "목차"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - href: index.ipynb
        text: "들어가는 글"
      - section: "1장 데이터 분석의 소개"
        contents:
          - contents/chap01/00_intro.ipynb
          - contents/chap01/01_introduction.ipynb
          - contents/chap01/02_devenv.ipynb
          - contents/chap01/99_closing.ipynb
      - section: "2장 Pandas를 이용한 기초 데이터 분석"
        contents:
          - contents/chap02/00_intro.ipynb
          - contents/chap02/99_closing.ipynb
      - section: "3장 Polars를 이용한 고속 데이터 분석"
        contents:
          - contents/chap03/00_intro.ipynb
          - contents/chap03/99_closing.ipynb
      - section: "4장 SqlAlchemy를 이용한 데이터베이스 연동"
        contents:
          - contents/chap04/00_intro.ipynb
          - contents/chap04/01_sqlalchemy_intro.ipynb
          - contents/chap04/02_sqlalchemy_core.ipynb
          - contents/chap04/03_sqlalchemy_orm.ipynb
          - contents/chap04/99_closing.ipynb
      - section: "5장 Alembic을 이용한 스키마 관리"
        contents:
          - contents/chap05/00_intro.ipynb
          - contents/chap05/99_closing.ipynb
      - section: "6장 Ibis를 이용한 데이터 분석"
        contents:
          - contents/chap06/00_intro.ipynb
          - contents/chap06/99_closing.ipynb
      - section: "7장 파일 데이터 저장소"
        contents:
          - contents/chap07/00_intro.ipynb
          - contents/chap07/01_s3.ipynb
          - contents/chap07/02_gspread.ipynb
          - contents/chap07/99_closing.ipynb

format:
  html:
    theme: cosmo
    css: web_resource/styles.css
    toc: true
    grid:
      sidebar-width: 390px
