project:
  type: website

language: ko.yml
date-format: iso

website:
  title: "데이터 플랫폼"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "데이터 저장소"
        contents:
          - contents/datastore/index.ipynb
          - contents/datastore/google_sheets.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
